input_file: ./data/sample_to_train.tsv
output_dir_name: outputs
delimiter: tab
batch_size: 64
dim_embed: 16
dim_hidden: 32
epochs: 2
target_column:
  name: quantity
  type: float
train_columns:
- name: ymd_date
  encoder_type: date
- name: day_of_week
  encoder_type: label_encoder
- name: store_id
  encoder_type: label_encoder
- name: long_catalog_name
  encoder_type: text_encoder
  max_length: 20
- name: mrating_excellent
  encoder_type: as_label
  coeff: 1
- name: mrating_good
  encoder_type: as_label
  coeff: 1
- name: mrating_ok
  encoder_type: as_label
  coeff: 1
- name: mrating_bad
  encoder_type: as_label
  coeff: 1
- name: mrating_awful
  encoder_type: as_label
  coeff: 1
- name: best_store
  encoder_type: as_label
  coeff: 1
- name: store_introduction
  encoder_type: text_encoder
  max_length: 20
- name: store_category1
  encoder_type: label_encoder
- name: store_category2
  encoder_type: label_encoder
- name: store_category3
  encoder_type: label_encoder
- name: store_review_rate
  encoder_type: as_label
  coeff: 100
- name: pmall_status
  encoder_type: label_encoder
- name: item_code
  encoder_type: label_encoder
- name: item_type
  encoder_type: label_encoder
- name: item_name
  encoder_type: text_encoder
  max_length: 20
- name: original_price
  encoder_type: as_label
  coeff: 1
- name: original_pricetax
  encoder_type: as_label
  coeff: 1
- name: headline
  encoder_type: text_encoder
  max_length: 20
- name: brand_code
  encoder_type: label_encoder
- name: delivery_type
  encoder_type: label_encoder
- name: product_category_id
  encoder_type: label_encoder
- name: gpath1
  encoder_type: label_encoder
- name: gpath2
  encoder_type: label_encoder
- name: gpath3
  encoder_type: label_encoder
- name: gpath4
  encoder_type: label_encoder
- name: gpath5
  encoder_type: label_encoder
- name: spec1
  encoder_type: label_encoder
- name: spec2
  encoder_type: label_encoder
- name: spec3
  encoder_type: label_encoder
- name: spec4
  encoder_type: label_encoder
- name: spec5
  encoder_type: label_encoder
- name: spec6
  encoder_type: label_encoder
- name: spec7
  encoder_type: label_encoder
- name: spec8
  encoder_type: label_encoder
- name: spec9
  encoder_type: label_encoder
- name: show_stock_type
  encoder_type: as_label
  coeff: 1
- name: final_pr_rate
  encoder_type: text_encoder
  max_length: 10
- name: brand_id
  encoder_type: label_encoder
- name: jan_code
  encoder_type: label_encoder
- name: y_shopping_display_flag
  encoder_type: label_encoder
- name: wish_count
  encoder_type: as_label
  coeff: 1
- name: discount_rate
  encoder_type: as_label
  coeff: 100
